### PR TITLE
add gitbucket-csvtsv-plugin and gitbucket-smiles-plugin

### PR DESCRIPTION
**Pull request by onukura**
This PR add plugins below to the community list.
- Plugin to render csv and tsv file https://github.com/onukura/gitbucket-csvtsv-plugin
- Plugin to render smiles file https://github.com/onukura/gitbucket-smiles-plugin

### CODE REVIEW

**Comment by onukura** [comment]
This one is better after https://github.com/gitbucket-plugins/gitbucket-plugins.github.io/pull/45 is checked and decided if merge or not.

**Comment by takezoe** [comment]
@onukura Merged #45. Could you revise this pull request?

**Comment by onukura** [comment]
@takezoe Thank you for merging #45. And I fixed this PR.

**Comment by takezoe** [comment]
Thanks for update!

**Pull request merged**
