### PR TITLE
Add embedded snipet plugin to list

### PR DESCRIPTION
**Pull request by onukura**
This PR add plugins below to the community list.
https://github.com/onukura/gitbucket-embedding-plugin

### CODE REVIEW

**Comment by takezoe** [comment]
Thanks! By the way, as you mentioned in README of this plugin, this feature might have to be implemented on GitBucket side. Do you have any concern about it?

**Comment by onukura** [comment]
@takezoe At first Thx for merge!

> By the way, as you mentioned in README of this plugin, this feature might have to be implemented on GitBucket side. Do you have any concern about it?

 Humm... This plugin just add JS on every page and have to search target DOM to replace with another DOM. So I thought it would be better for performance if it's done by renderer.  Do you think snippet is ok with this way??

**Comment by onukura** [comment]
But at same time this way is useful too. It  works every `.markdown-body.p.a` in issue, PR, wiki, repo/README.

**Comment by onukura** [comment]
@takezoe I think this discussion should be at https://github.com/gitbucket/gitbucket/issues/2485. So I will put comment from now.

**Comment by takezoe** [comment]
> I think this discussion should be at gitbucket/gitbucket#2485. So I will put comment from now.

That makes sense. Let's discuss there.

**Pull request merged**
